### ISSUE TITLE
Issue with Firefox on Kubuntu OS

### ISSUE THREAD

**Issue by mtancoigne** [DominikSerafin/vuebar#12]
Firefox's display for the scrollbar is based on the system preferences. That means that sometimes, the scrollbar is not displayed, even with `overflow-y:scroll`.

When the content is not long enough for the scrollbar to appear, the content width (`100%+17px`) make the content to overflow...

I really like the idea of this hack to use the native scroll :/
![selection_064](https://user-images.githubusercontent.com/1732268/28241010-41d019fa-698c-11e7-9a77-8199c4422909.png)

**Comment by DominikSerafin** [comment]
Hey @mtancoigne thanks so much for reporting it!

Can I ask you which System, Firefox versions and Vuebar version is this issue present on?

**Comment by mtancoigne** [comment]
Yes, of course (sorry for not mentioning it before)
I'm using **Firefox 54** on a **kubuntu 17.04** and **vuebar 0.0.11**

**Comment by DominikSerafin** [comment]
@mtancoigne thanks for the info - I was a little confused where you can set scrollbar preference OS wide, and it's seems that's a kubuntu thing.

As for the issue itself, try upgrading to newest Vuebar. Since version 0.0.12 it detects scrollbar size automatically.

Please let me know if that helps.

**Comment by mtancoigne** [comment]
Thanks, it seems better ! I'll come back if there is anything wrong.
