### ISSUE TITLE
Flexbox config broken

### ISSUE THREAD

**Issue by nicolasvahidzein** [DominikSerafin/vuebar#13]
Hey Dominik, how are you?

Quick question, when i add v-bar to a nicely configured flexbox container, it breaks it and overwrites my config.

Any idea how i can fix this?

**Comment by DominikSerafin** [comment]
Hey @nicolasvahidzein,

It's stated in docs and it's normal behavior.

> Element el1 has programmatically added styles position: relative and overflow: hidden so you can't change them without using !important. But you shouldn't do it anyway - your scrollbar will break.

> Element el2 has programmatically added styles overflow-x: hidden, overflow-y: scroll, height: 100%, -ms-overflow-style: scrollbar and width which value depends on browser.

> If the original browser scrollbar is floated/overlayed (-ms-autohiding-scrollbar, touch devices, etc.) then el2 also has padding-right changed.

There's no other way around this - to retain native scroll behavior Vuebar needs to style its elements in a certain way a bit.

You can play with wrapping your container in another element or try other applying other CSS to your container.
