### ISSUE TITLE
Vuebar for a textfield

### ISSUE THREAD

**Issue by nicolasvahidzein** [DominikSerafin/vuebar#14]
Hello Dominik,

i tried implement the vuebar for a textfield, but i don't really know where to put my tags. Can you help please?

**Comment by DominikSerafin** [comment]
Vuebar doesn't yet support textarea element so the behavior will be a little buggy. 

Nevertheless, you can do it like this: https://jsfiddle.net/mv48bhf5/ 

You can also always style your scrollbars using ::-webkit-scrollbar pseudo styling, like this: https://jsfiddle.net/mv48bhf5/1/

**Comment by nicolasvahidzein** [comment]
Love the first one, will implement and keep you posted. Thanks Dominik!!!

**Comment by nicolasvahidzein** [comment]
Ok we are almost there, the only thing is that i have your scrollbar and the default one overlapping. In your jsfiddle it works but in my project overflow get over written by scroll as soon as i add v-bar to the div. Before that all is nicely displayed without a scrollbar waiting for your custom scrollbar to appear.

**Comment by nicolasvahidzein** [comment]
Also for the textfield, overflow auto does not work, i need to use hidden.

**Comment by nicolasvahidzein** [comment]
Dominik, hello, i still need your help to fix this. Pretty please with a cherry on top :)

**Comment by DominikSerafin** [comment]
Hey @nicolasvahidzein, I'm really sorry I can't help you with that - Vuebar just doesn't support textareas -  so not everything is possible to do in that case.

**Comment by nicolasvahidzein** [comment]
Well let's look into it, anything i can do to help? I'm no expert but i like finding solutions. Tell me what to do and i'll check it out. Adding support for text area is very important, your module is already so good, why not make it perfect?

**Comment by nicolasvahidzein** [comment]
Dominik?
