### ISSUE TITLE
Box-sizing

### ISSUE THREAD

**Issue by DominikSerafin** [DominikSerafin/vuebar#15]
1. Find a way to not use content box

2. Test vuebar on default *{box-sizing:content-box}

**Comment by DominikSerafin** [comment]
Moved into roadmap https://github.com/DominikSerafin/vuebar/projects/1

**Comment by VRuzhentsov** [comment]
Hi
Have some issues with `content-box` on safari, it has different rendering with chrome, and in chrome does not appends `box-sizing` 
Of course i can override by `!important`, but why we use `content-box` ?

**Comment by DominikSerafin** [comment]
@VRuzhentsov, which version of Vuebar you're using? There was a related (loosely) problem to `box-sizing` in Safari with version 0.0.17. But it was fixed in version 0.0.18. 

Could you tell me what's the exact problem for you?

You could also create minimal reproduction, it would help me greatly in helping you.

Here are good starting points: 
http://jsfiddle.net/u94ns8jc/1/
https://www.webpackbin.com/bins/-Kyoqtm8CbjpkYegi7mF

**Comment by VRuzhentsov** [comment]
@DominikSerafin 
take a look please
http://jsfiddle.net/Vitalii_Ruzhentsov/n3hyLqp0/2/
In Chrome and Mac Safari - `box-sizing` is different

**Comment by DominikSerafin** [comment]
@VRuzhentsov thanks, but it's actually intended behavior. 

Safari (by default) has overlaying native scrollbars. In that case Vuebar hides them using `padding` + by forcing `box-sizing`. 

Chrome has standard native scrollbars that are in the document flow (that are not overlayed over container). In this case, Vuebar detects their width and hides them using `overflow: hidden`, without applying any `padding`. 

I was actually more curious why you need to have different `box-sizing` in that specific element? Are any workarounds not viable for you? (E.g. wrapping Vuebar container in another container?)

**Comment by VRuzhentsov** [comment]
@DominikSerafin 
Everywhere it would be enought `box-sizing: border-box` for me. And this content wrapper is workaround about sidebar ahd header, because they are fixed, and content needed to be under header (z-index) with scrolling, but save left padding from sidebar, for quick adaptive styles.

But vuebar overrides `box-sizing` to `content-box` (safari only)
