### ISSUE TITLE
The question about refreshScrollbar

### ISSUE THREAD

**Issue by doublestaiwan** [DominikSerafin/vuebar#23]
Hi,
This project is so useful.

But I have a problem about the **refreshScrollbar** function.

Here is my example
https://codepen.io/SSTLin/pen/xLYbJg

In the example, Click nav_3 to show or hide content.
The scroll content's height change by CSS and animate by CSS transition.
Becaue of the CSS transition delay 0.5 sec, but vuebar change scroll bar's state immediately.

I try to add setTimeout as follows:

        function refreshScrollbar(el, options){

            var options = options ? options : {};

            if (options.immediate) {
                computeVisibleArea(el);
                computeBarTop(el);
                computeBarHeight(el);
                updateDragger(el);
            }
            var state = getState(el);
            Vue.nextTick(function(){
                setTimeout(function(){
                    if ( !getState(el) ) { return false }
                    computeVisibleArea(el);
                    computeBarTop(el);
                    computeBarHeight(el);
                    updateDragger(el);
                }, state.config.refreshTimeout);
                
            }.bind(this));
        }

Try search the key word **, refreshTimeout: 0** at example's js, and change the value 0 to 600, and it works fine.
Is this an issue?
or
I did try public method as follows:
setTimeout(function(){ 
  Vue.vuebar.refreshScrollbar(DOM Element, options); 
}, 600);
But It doesn't work, is there any example?

Thanks.

**Comment by DominikSerafin** [comment]
The only issue in your example that I can see is that Vuebar doesn't update when you close that "nav" element. To update it manually you need use the `refreshScrollbar` method or just do `$forceUpdate()` on the Vue component containing Vuebar after transition end.
