### ISSUE TITLE
In macOS, vuebar can't work as normal.

### ISSUE THREAD

**Issue by zhaozhe0831** [DominikSerafin/vuebar#24]
```html
<div v-bar> <!-- el1 -->
  <div> <!-- el2 -->
    <!-- In macOS, content Dom position:relatve. -->
     <div style="position:relative;"></div>
    <!-- content -->
  </div>
  <!-- dragger will be automatically added here -->
</div>
```
if content has css "position:relative", vuebar can't work as normal, in macOS.
But work well in windows.

![image](https://user-images.githubusercontent.com/12945873/29556151-84f7b772-8757-11e7-9c8f-ae92ca96bd07.png)

Is it a bug ? HTML CSS bug OR vuebar bug?

![wx20170822-163917](https://user-images.githubusercontent.com/12945873/29556764-72423a06-8759-11e7-8e2b-c00a60e115f1.jpg)

**Comment by doublestaiwan** [comment]
try this
<div v-bar="{useScrollbarPseudo: true}">

**Comment by zhaozhe0831** [comment]
resolve.
thank you !
