### ISSUE TITLE
Dragger misaligned with mouse pointer on retina resolution monitors

### ISSUE THREAD

**Issue by jeppebemad** [DominikSerafin/vuebar#3]
Hi, thanks for contributing this plugin!
Using Chrome, dragging the dragger does not work as expected: The drag-event seems to be offset.

Steps to reproduce: 

1. Go to first example on https://github.serafin.io/vuebar/#examples
2. Click and drag the dragger downwards.

Result:

Dragger jumps to the bottom of the scrollable element along with the content. From here only able to scroll up, but this is offset by what looks like the height of the scrollable element.

It might be the "jump" when clicking the scrollbar causing the issues?

Thanks.

**Comment by DominikSerafin** [comment]
Hello, thanks for adding the issue!

Can I ask what OS and what Chrome version are you exactly using?

I can't to reproduce this issue in Windows 10 + Chrome 58:

![](http://i.imgur.com/e0UfLS9.gif)

Thank you

**Comment by jeppebemad** [comment]
Also windows 10 here. I was using Chrome 58.0.3029.110, but just updated to 59.0.3071.104. Still same issue. 

BUT, I realize now what causes the issue. I'm on a Macbook pro with retina screen. It's the retina DPI settings on the retina screen that causes the calculations to go sour. If I move the window to my secondary non-retina screen, all is well.

**Comment by DominikSerafin** [comment]
Thank you @jeppebemad for providing more info 😁 

I'll get to it as soon as possible. If someone want to tackle this on their own then pull request is welcome.

Thanks!

**Comment by DominikSerafin** [comment]
Hey @jeppebemad 

I might've fixed it with https://github.com/DominikSerafin/vuebar/commit/65185345a737bee69f32f39f159c22b7b8c72746. Could you test if it works now on your retina display now?

**Comment by jeppebemad** [comment]
Thanks @DominikSerafin - it worked beautifully! A simple fix like that indicate good code ;)
