### ISSUE TITLE
On MacOS container with vuebar is larger than it should be.

### ISSUE THREAD

**Issue by Aterr** [DominikSerafin/vuebar#31]
Hi there!
I am facing the issue, when using this plugin on mac.

On windows in all browsers everything is looking just fine, but on mac My container is about 15px wider than it should be. Any thoughts ? Thanks in advice :)

**Comment by DominikSerafin** [comment]
Hey @Aterr, what do you mean by "container"? `el1`, `el2` or `dragger`?

**Comment by Aterr** [comment]
Hi @DominikSerafin, i mean the .vb-content div :) It's probably el2

**Comment by Aterr** [comment]
Fixed it :)
I should avoid padding property on .vb-content
