### ISSUE TITLE
can you add an enable option?

### ISSUE THREAD

**Issue by 79229788** [DominikSerafin/vuebar#35]
Sorry, I am from China, my English is very terrible,  can only  rely on Google translation. And  can you add an enable option? such as,
use v-bar = "false", the default is true. And then you can only write a return clause in vue`s bind method, it is simple to be able to do.
Because I hope that when browsing the phone pages do not enable the plug-in, because， use of native scroll bar may be better。

And horizontal scroll bar also hope to be able to provide early, really need, thanks

Maybe, the translation  is very funny！😂

**Comment by DominikSerafin** [comment]
For the phones scrollbar there is a `overrideFloatingScrollbar` customization options. I hope it'll help in your case.

As for the proper "enable" option and horizontal scrollbar - they'll be added in Vuebar 2.0: https://github.com/DominikSerafin/vuebar/issues/32
