### ISSUE TITLE
Doesn't work on modal window

### ISSUE THREAD

**Issue by romanrei** [DominikSerafin/vuebar#37]
Hi, nice scrollbar works great on simple divs, but i have a problem. it doesn't work on modal window.
Well it works, but not as expected. I still see default scrollbar together with new one. 
If i enable _useScrollbarPseudo: true_ it will work, but only in chrome..

**Comment by DominikSerafin** [comment]
Could you provide jsfiddle with minimal reproduction? Without it I'm not able to help you.

Here's good starting point: https://jsfiddle.net/50wL7mdz/72834/
