### ISSUE TITLE
how to know when vuebar become 'active'?

### ISSUE THREAD

**Issue by guykatz** [DominikSerafin/vuebar#39]
hi;
I want to display a button only after scroll starts and make it invisible again when scrollTo is set to 0 on the element (el2.scrollTop=0)
how do I track the scrolling in vuebar? I need to know when someone actually started scrolling.
currently I binded a scroll event to vuebar's el2 and I check el2's scrollTop.
is this a valid option? the only options?
thanks

**Comment by DominikSerafin** [comment]
Hi @guykatz. That's exactly why this library doesn't hijack scrolling, but works on top of native scrolling behavior - to allow listening for native scroll events. So your solution is the most valid as it can be.
