### ISSUE TITLE
Overflowing content on devices with hidden (overlaying) scrollbars

### ISSUE THREAD

**Issue by aeharding** [DominikSerafin/vuebar#4]
Hi there,

Please see the screenshot below to see the content overflowing the container to the right making it difficult/impossible to read. It is like this on all the examples.

This is latest Chrome on Mac OS X.

Please let me know if you have any questions or if you want me to test anything out.

![image](https://user-images.githubusercontent.com/2166114/27654382-b2367244-5c07-11e7-95ad-0eb77693db80.png)

Thanks!
Alex

**Comment by aeharding** [comment]
This is a solution that a different scroll library I saw used: https://github.com/felixexter/scrollbarWidth

**Comment by DominikSerafin** [comment]
Hello @aeharding, thanks for spotting that. I'll fix that as soon as it's possible for me. For now you can use `useScrollbarPseudo` option that should fix that.

Could you tell me on what display/monitor you saw that issue?

**Comment by aeharding** [comment]
@DominikSerafin This is on my 15" macbook pro (latest one). Hope that helps!

**Comment by DominikSerafin** [comment]
Hello @aeharding! 

I've updated VueBar to 0.0.12 which hopefully should fix that issue. And there's also new `overrideFloatingScrollbar` option relevant to this.

Could you confirm that this problem is now fixed for you?

**Comment by aeharding** [comment]
Quick look shows it works for me!

I'll close this issue and I'll let you know if I have issues after updating vue-bar in my use case.

Thank you!
