### ISSUE TITLE
Using flex to set height: 100% in Safari browsers won't work

### ISSUE THREAD

**Issue by yansenlei** [DominikSerafin/vuebar#56]
Is there any good solution to safari's flexbox height bug?

**Comment by yansenlei** [comment]
Hi, @DominikSerafin 
Using `flex` to set `height: 100%` in Safari browsers won't work. This is Safari's [bug](https://bugs.webkit.org/show_bug.cgi?id=137730), and I queried some of the solutions:
https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent
https://www.labsrc.com/safari-full-height-flexbox-children/

**Comment by DominikSerafin** [comment]
Hi @yansenlei if you still have a problem with this - could you provide me minimal reproduction (on JSFiddle, CodeSandbox, or similar) that showcases this problematic behavior?

**Comment by yansenlei** [comment]
Hi @DominikSerafin 
I tried again and found that it worked in Safari...
http://jsfiddle.net/leiys/agv130y4/11/
