### ISSUE TITLE
Content visible after axios call, but no scrollbar

### ISSUE THREAD

**Issue by rowild** [DominikSerafin/vuebar#59]
I have a list of news items that, once loaded, make up a list that overflows the page height and therefore need a scroller. The news a loaded via axios. The simple setup up won't show a scrollbar, So I tried to use a refresh in axios' finally:
```js
_self = this
axios().finally(() => {
   _self.$vuebar.refreshScrollbar('.o-content__aside', {
              resizeRefresh: true,
              resizeBounce: true
            })
}
```
But to no avail. The sroller classes remain "v-invisible", "'height: 0px" etc.
What do I have to do to make that work?

**Comment by DominikSerafin** [comment]
Hi @rowild, sorry for not getting back earlier to you. If for some chance you still need help with this - could you provide minimal repro that showcases this problematic behavior?

**Comment by rowild** [comment]
Hi, Dominik! I should have closed this earlier. I think - if I remember correctly - I needed to call some update() function after loading. It eventually worked fine.
I am closing this issue no, ok?

Thank you for your component!!!
