### ISSUE TITLE
Box-sizing: content-box breaks layout

### ISSUE THREAD

**Issue by 7iomka** [DominikSerafin/vuebar#63]
In my site i have css rule in reset css:
`*, *:before, *:after { box-sizing: inherit }`
and 
`html {box-sizing: border-box;}`

**I use your plugin to instead of native page scrollbar;**
Plugin make this:
on .vb-content put css
```
    display: block;
    overflow: hidden scroll;
    height: 100%;
    width: 100%;
    box-sizing: content-box;
    padding-right: 20px;
```

http://s1.micp.ru/FpsfI.jpg

and all layout, like a .container-fluid from bootstrap breaks it layout :(

**Comment by DominikSerafin** [comment]
@7iomka you can just redeclare `box-sizing: border-box` again on your `site-content` element.
