### ISSUE TITLE
How can i autoscroll div with v-bar to some selected element?

### ISSUE THREAD

**Issue by alexdpts** [DominikSerafin/vuebar#65]
Markup, for example:
````
<div style="width:100%;height:100px;" v-bar>
   <div>
    <ul>
        <li><span>One</span></li>
        <li><span>Two</span>
              <ul>
                  <li><span>Two One</span></li>
                  <li><span>Two Two</span></li>
                  ....
                  <li><span>Two N</span></li>
              </ul>
        </li>
        ...
        <li><span class="selected">N</span>
        ...
    </ul>
  </div>
</div>


How can i scroll div content to element with class="selected"?

**Comment by DominikSerafin** [comment]
Hey @alexdpts, Vuebar doesn't interfere with native scroll events. So you can just use native JS DOM scrolling events & methods. 

In case of Vuebar - the inner wrapper element is a 'scrollable' element (child of element with `v-bar` directive), so you can `ref` it and then e.g. use `scrollTop`: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop
