### ISSUE TITLE
[Question] Scroll Listeners and position manipulation

### ISSUE THREAD

**Issue by hfalucas** [DominikSerafin/vuebar#7]
Hello guys, this plugin looks really good :)

Just two quick questions:

1. Is there any plans to add scroll listeners? 
(Ex: Scroll reach bottom, Scroll reach top - good for infinite scrolls)

2. A way to set the scroll to a specific position?
(Ex: 'Top', 'Bottom' or just a number - neat to chat apps or navigate to sections)

Keep up with the great work

Cheers

**Comment by DominikSerafin** [comment]
Hello @hfalucas 

The main feature of this library is that it doesn't change native scroll behavior. It only provides the styleable "dragger" element that gets synced with the native browser scroll. So both of your questions are easily implemented using standard practices.

1. Just use `scroll` event listener (`v-bind:scroll` or `@scroll` in Vue). See [StackOverflow answer](https://stackoverflow.com/a/34550171/3143704) and [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Events/scroll).
2. Change `scrollTop` property of DOM element to your wanted value. See [PlainJS article](https://plainjs.com/javascript/styles/get-and-set-scroll-position-of-an-element-26/) and [MDN documentation](https://developer.mozilla.org/en/docs/Web/API/Element/scrollTop).

With that in mind - in future I might implement some helper utilities - especially for the second case.
