### ISSUE TITLE
Smooth scroll at mobile

### ISSUE THREAD

**Issue by allmightdev** [DominikSerafin/vuebar#76]
Hello _DominikSerafin_, ш have a problem with scrolling on mobile devices, it works, but I would like to know if it can be done with a little inertia

It works perfectly on your website, but I haven’t found any settings that could help me.  Would appreciate help

P.S.  example you can look at "https://thedosvid.com", if you turn on site at mobile, thanks a lot

**Comment by scherii** [comment]
Hi @allmightdev 
Could it be that by «inertia» you're talking about this proprietary feature?
https://developer.mozilla.org/en/docs/Web/CSS/-webkit-overflow-scrolling
