### ISSUE TITLE
Using vuebar for a horizontal scrollbar

### ISSUE THREAD

**Issue by mediagraphik** [DominikSerafin/vuebar#86]
Hello,

is it possible to use vuebar for a horizontal scrollbar?
Would be really helpful for tables in Mobile.
Otherwise, it would be great if that feature is integrated into a future version.

**Comment by DominikSerafin** [comment]
While not yet finished (almost), you can try to use the development version of Vuebar which supports horizonstal scrollbar: https://github.com/DominikSerafin/vuebar/tree/development

Lots of demos in docs/demotests.html

---

Closing this as it's duplicate of https://github.com/DominikSerafin/vuebar/issues/27
